3 add micropost api
KituneUdon/twiiter-like-sns pull request #21
Opened 2021-04-08 10:41 UTC by kenichi-morihara

# 目的
Micropost一覧取得APIの実装
# 達成条件
フロント側でAPIが実行してテストデータの取得、表示ができること
# 実装の概要
maicropostテーブルとuserテーブルをjoinして全件取得して返すように実装
# レビューして欲しいところ
フロントからAPIを実行してdatabase/init/ddl.sqlのテストデータ通りに
データを取得、表示できるか確認して欲しいです

2021-04-08 13:33 UTC, KituneUdon commented
2点対応してほしいことがあります。

1. `git rebase main`でmainブランチの最新情報を取り込んでほしい
2. APIサーバは3000番で起動してほしい

1.
フロントエンドのコードが古いので、
フロントエンドからAPIを叩くことができない。
最新のフロントエンドのコードを持ってくるために`git rebase main`を実行してからプルリクエストを出してほしい。

2.
3ヶ月ほど前ですが定例の中でフロントエンド：4000、バックエンド：3000にすると決めたのでそれに沿っていただけると助かる。
https://scrapbox.io/foobaabaz/20210115_%E5%AE%9A%E4%BE%8B

goで習慣的に使うポートが80なのであれば、そちらに合わせます。

2021-04-29 13:14 UTC, KituneUdon commented
`docker-compose up`した際にDBが立ち上がっていないのでエラー吐いて終了します

```
❯ docker-compose up
Creating network "twitter-like-sns_default" with the default driver
Pulling mysql (mysql:latest)...
latest: Pulling from library/mysql
f7ec5a41d630: Pull complete
9444bb562699: Pull complete
6a4207b96940: Pull complete
181cefd361ce: Pull complete
8a2090759d8a: Pull complete
15f235e0d7ee: Pull complete
d870539cd9db: Pull complete
493aaa84617a: Pull complete
bfc0e534fc78: Pull complete
fae20d253f9d: Pull complete
9350664305b3: Pull complete
e47da95a5aab: Pull complete
Digest: sha256:04ee7141256e83797ea4a84a4d31b1f1bc10111c8d1bc1879d52729ccd19e20a
Status: Downloaded newer image for mysql:latest
Creating myapp-db ... done
Creating twitter-like-sns_golang_1 ... done
Attaching to myapp-db, twitter-like-sns_golang_1
myapp-db  | 2021-04-29 13:08:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
myapp-db  | 2021-04-29 13:08:23+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
myapp-db  | 2021-04-29 13:08:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
myapp-db  | 2021-04-29 13:08:23+00:00 [Note] [Entrypoint]: Initializing database files
myapp-db  | 2021-04-29T13:08:23.317261Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.24) initializing of server in progress as process 41
myapp-db  | 2021-04-29T13:08:23.321554Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-04-29T13:08:23.567936Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-04-29T13:08:24.628925Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
golang_1  | 2021/04/29 13:08:24 DB connection failed dial tcp 172.20.0.2:3306: connect: connection refused
golang_1  | exit status 1
twitter-like-sns_golang_1 exited with code 1
myapp-db  | 2021-04-29 13:08:26+00:00 [Note] [Entrypoint]: Database files initialized
myapp-db  | 2021-04-29 13:08:26+00:00 [Note] [Entrypoint]: Starting temporary server
myapp-db  | 2021-04-29T13:08:26.704488Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.24) starting as process 86
myapp-db  | 2021-04-29T13:08:26.733212Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-04-29T13:08:26.843243Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-04-29T13:08:26.932757Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-04-29T13:08:27.054238Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-04-29T13:08:27.054614Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-04-29T13:08:27.057308Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-04-29T13:08:27.097401Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.24'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
myapp-db  | 2021-04-29 13:08:27+00:00 [Note] [Entrypoint]: Temporary server started.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
myapp-db  | 
myapp-db  | 2021-04-29 13:08:28+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
myapp-db  | 
myapp-db  | 
myapp-db  | 2021-04-29 13:08:28+00:00 [Note] [Entrypoint]: Stopping temporary server
myapp-db  | 2021-04-29T13:08:28.443010Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.24).
myapp-db  | 2021-04-29T13:08:29.570164Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.24)  MySQL Community Server - GPL.
myapp-db  | 2021-04-29 13:08:30+00:00 [Note] [Entrypoint]: Temporary server stopped
myapp-db  | 
myapp-db  | 2021-04-29 13:08:30+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
myapp-db  | 
myapp-db  | 2021-04-29T13:08:30.684714Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.24) starting as process 1
myapp-db  | 2021-04-29T13:08:30.707986Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-04-29T13:08:30.816091Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-04-29T13:08:30.911452Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-04-29T13:08:31.035694Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-04-29T13:08:31.035993Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-04-29T13:08:31.039262Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-04-29T13:08:31.059387Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.24'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
^CGracefully stopping... (press Ctrl+C again to force)
Stopping myapp-db                  ... done

```

2021-05-18 16:44 UTC, kenichi-morihara commented
@KituneUdon 指摘箇所修正したのでレビューお願いします

2021-05-20 05:23 UTC, KituneUdon commented
# 問題
`docker-compose up`でサーバは起動していると思われるが、ホストからアクセスできない

# 実行コマンド
`docker-compose build`
`docker-compose up`
## 結果
```
twitter-like-sns on  3_Add_MicropostAPI [!] 
❯ docker-compose build
mysql uses an image, skipping
Building golang
Step 1/9 : FROM golang:1.16.0-alpine3.13
 ---> 696265badec1
Step 2/9 : RUN apk add --update --no-cache ca-certificates git
 ---> Running in 3308ccc6183e
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r3)
(2/6) Installing nghttp2-libs (1.42.0-r1)
(3/6) Installing libcurl (7.76.1-r0)
(4/6) Installing expat (2.2.10-r1)
(5/6) Installing pcre2 (10.36-r0)
(6/6) Installing git (2.30.2-r0)
Executing busybox-1.32.1-r3.trigger
OK: 19 MiB in 21 packages
Removing intermediate container 3308ccc6183e
 ---> 795e251d6ec2
Step 3/9 : RUN mkdir /go-app
 ---> Running in 034cc71bacba
Removing intermediate container 034cc71bacba
 ---> 04b7f794d5f9
Step 4/9 : WORKDIR /go-app
 ---> Running in 210ea62dc7aa
Removing intermediate container 210ea62dc7aa
 ---> 5030904e9795
Step 5/9 : COPY go.mod .
 ---> 875c4745fff6
Step 6/9 : COPY go.sum .
 ---> 11d59b9a14b8
Step 7/9 : RUN go mod download
 ---> Running in 55064bdf8203
Removing intermediate container 55064bdf8203
 ---> 9cc675c67117
Step 8/9 : COPY . .
 ---> c604e654569e
Step 9/9 : CMD ["go", "run", "main.go"]
 ---> Running in 0d734dbcd745
Removing intermediate container 0d734dbcd745
 ---> 2a2472a100d8
Successfully built 2a2472a100d8
Successfully tagged twitter-like-sns_golang:latest

twitter-like-sns on  3_Add_MicropostAPI took 6s 
❯ docker-compose up
Creating network "twitter-like-sns_default" with the default driver
Pulling mysql (mysql:latest)...
latest: Pulling from library/mysql
69692152171a: Pull complete
1651b0be3df3: Pull complete
951da7386bc8: Pull complete
0f86c95aa242: Pull complete
37ba2d8bd4fe: Pull complete
6d278bb05e94: Pull complete
497efbd93a3e: Pull complete
f7fddf10c2c2: Pull complete
16415d159dfb: Pull complete
0e530ffc6b73: Pull complete
b0a4a1a77178: Pull complete
cd90f92aa9ef: Pull complete
Digest: sha256:d50098d7fcb25b1fcb24e2d3247cae3fc55815d64fec640dc395840f8fa80969
Status: Downloaded newer image for mysql:latest
Creating myapp-db ... done
Creating twitter-like-sns_golang_1 ... done
Attaching to myapp-db, twitter-like-sns_golang_1
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Initializing database files
myapp-db  | 2021-05-20T05:18:09.216843Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 42
myapp-db  | 2021-05-20T05:18:09.223434Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:09.521811Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
golang_1  | 2021/05/20 05:18:10 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | 2021-05-20T05:18:10.848011Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
myapp-db  | 2021-05-20 05:18:12+00:00 [Note] [Entrypoint]: Database files initialized
myapp-db  | 2021-05-20 05:18:12+00:00 [Note] [Entrypoint]: Starting temporary server
myapp-db  | 2021-05-20T05:18:12.857606Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 87
myapp-db  | 2021-05-20T05:18:12.886224Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:12.989983Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-05-20T05:18:13.081085Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-05-20T05:18:13.200816Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-05-20T05:18:13.201347Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-05-20T05:18:13.204676Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-05-20T05:18:13.248018Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
myapp-db  | 2021-05-20 05:18:13+00:00 [Note] [Entrypoint]: Temporary server started.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
golang_1  | 2021/05/20 05:18:13 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
myapp-db  | 
myapp-db  | 2021-05-20 05:18:14+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
myapp-db  | 
myapp-db  | 
myapp-db  | 2021-05-20 05:18:14+00:00 [Note] [Entrypoint]: Stopping temporary server
myapp-db  | 2021-05-20T05:18:14.623750Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.25).
myapp-db  | 2021-05-20T05:18:15.743778Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
myapp-db  | 2021-05-20 05:18:16+00:00 [Note] [Entrypoint]: Temporary server stopped
myapp-db  | 
myapp-db  | 2021-05-20 05:18:16+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
myapp-db  | 
golang_1  | 2021/05/20 05:18:16 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | 2021-05-20T05:18:16.876508Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
myapp-db  | 2021-05-20T05:18:16.896495Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:17.001066Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-05-20T05:18:17.090697Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-05-20T05:18:17.198900Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-05-20T05:18:17.199177Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-05-20T05:18:17.201889Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-05-20T05:18:17.216929Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
golang_1  | 2021/05/20 05:18:19 MySQLまだ? <nil>
```

## curlでアクセスした結果
```
❯ curl http://127.0.0.1:3000
curl: (56) Recv failure: 接続が相手からリセットされました

```

2021-05-20 05:54 UTC, KituneUdon requested changes
# 問題
`docker-compose up`でサーバは起動していると思われるが、ホストからアクセスできない

## 実行コマンド
`docker-compose build`
`docker-compose up`
### 結果
```
twitter-like-sns on  3_Add_MicropostAPI [!] 
❯ docker-compose build
mysql uses an image, skipping
Building golang
Step 1/9 : FROM golang:1.16.0-alpine3.13
 ---> 696265badec1
Step 2/9 : RUN apk add --update --no-cache ca-certificates git
 ---> Running in 3308ccc6183e
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r3)
(2/6) Installing nghttp2-libs (1.42.0-r1)
(3/6) Installing libcurl (7.76.1-r0)
(4/6) Installing expat (2.2.10-r1)
(5/6) Installing pcre2 (10.36-r0)
(6/6) Installing git (2.30.2-r0)
Executing busybox-1.32.1-r3.trigger
OK: 19 MiB in 21 packages
Removing intermediate container 3308ccc6183e
 ---> 795e251d6ec2
Step 3/9 : RUN mkdir /go-app
 ---> Running in 034cc71bacba
Removing intermediate container 034cc71bacba
 ---> 04b7f794d5f9
Step 4/9 : WORKDIR /go-app
 ---> Running in 210ea62dc7aa
Removing intermediate container 210ea62dc7aa
 ---> 5030904e9795
Step 5/9 : COPY go.mod .
 ---> 875c4745fff6
Step 6/9 : COPY go.sum .
 ---> 11d59b9a14b8
Step 7/9 : RUN go mod download
 ---> Running in 55064bdf8203
Removing intermediate container 55064bdf8203
 ---> 9cc675c67117
Step 8/9 : COPY . .
 ---> c604e654569e
Step 9/9 : CMD ["go", "run", "main.go"]
 ---> Running in 0d734dbcd745
Removing intermediate container 0d734dbcd745
 ---> 2a2472a100d8
Successfully built 2a2472a100d8
Successfully tagged twitter-like-sns_golang:latest

twitter-like-sns on  3_Add_MicropostAPI took 6s 
❯ docker-compose up
Creating network "twitter-like-sns_default" with the default driver
Pulling mysql (mysql:latest)...
latest: Pulling from library/mysql
69692152171a: Pull complete
1651b0be3df3: Pull complete
951da7386bc8: Pull complete
0f86c95aa242: Pull complete
37ba2d8bd4fe: Pull complete
6d278bb05e94: Pull complete
497efbd93a3e: Pull complete
f7fddf10c2c2: Pull complete
16415d159dfb: Pull complete
0e530ffc6b73: Pull complete
b0a4a1a77178: Pull complete
cd90f92aa9ef: Pull complete
Digest: sha256:d50098d7fcb25b1fcb24e2d3247cae3fc55815d64fec640dc395840f8fa80969
Status: Downloaded newer image for mysql:latest
Creating myapp-db ... done
Creating twitter-like-sns_golang_1 ... done
Attaching to myapp-db, twitter-like-sns_golang_1
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
myapp-db  | 2021-05-20 05:18:09+00:00 [Note] [Entrypoint]: Initializing database files
myapp-db  | 2021-05-20T05:18:09.216843Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 42
myapp-db  | 2021-05-20T05:18:09.223434Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:09.521811Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
golang_1  | 2021/05/20 05:18:10 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | 2021-05-20T05:18:10.848011Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
myapp-db  | 2021-05-20 05:18:12+00:00 [Note] [Entrypoint]: Database files initialized
myapp-db  | 2021-05-20 05:18:12+00:00 [Note] [Entrypoint]: Starting temporary server
myapp-db  | 2021-05-20T05:18:12.857606Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 87
myapp-db  | 2021-05-20T05:18:12.886224Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:12.989983Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-05-20T05:18:13.081085Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-05-20T05:18:13.200816Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-05-20T05:18:13.201347Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-05-20T05:18:13.204676Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-05-20T05:18:13.248018Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
myapp-db  | 2021-05-20 05:18:13+00:00 [Note] [Entrypoint]: Temporary server started.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
golang_1  | 2021/05/20 05:18:13 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
myapp-db  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
myapp-db  | 
myapp-db  | 2021-05-20 05:18:14+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
myapp-db  | 
myapp-db  | 
myapp-db  | 2021-05-20 05:18:14+00:00 [Note] [Entrypoint]: Stopping temporary server
myapp-db  | 2021-05-20T05:18:14.623750Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.25).
myapp-db  | 2021-05-20T05:18:15.743778Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
myapp-db  | 2021-05-20 05:18:16+00:00 [Note] [Entrypoint]: Temporary server stopped
myapp-db  | 
myapp-db  | 2021-05-20 05:18:16+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
myapp-db  | 
golang_1  | 2021/05/20 05:18:16 MySQLまだ? dial tcp 172.20.0.2:3306: connect: connection refused
myapp-db  | 2021-05-20T05:18:16.876508Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
myapp-db  | 2021-05-20T05:18:16.896495Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
myapp-db  | 2021-05-20T05:18:17.001066Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
myapp-db  | 2021-05-20T05:18:17.090697Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
myapp-db  | 2021-05-20T05:18:17.198900Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
myapp-db  | 2021-05-20T05:18:17.199177Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
myapp-db  | 2021-05-20T05:18:17.201889Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
myapp-db  | 2021-05-20T05:18:17.216929Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
golang_1  | 2021/05/20 05:18:19 MySQLまだ? <nil>
```

## curlでアクセスした結果
```
❯ curl http://127.0.0.1:3000
curl: (56) Recv failure: 接続が相手からリセットされました
```

# 原因
APIのコードが8080番で動いている

## 証拠
lsofコマンドを用いてポートを確認したところ`http-alt`(8080)を利用していることが判明
※lsofはalpineに最初から入っていないので`apk add lsof`で入れた
```
/go-app # lsof -i
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
main    179 root    3u  IPv4  94876      0t0  TCP bb90c4f2d0b2:59594->myapp-db.twitter-like-sns_default:mysql (ESTABLISHED) [...]

2021-05-20 13:13 UTC, KituneUdon submitted a review, later dismissed
フロントエンドから接続できて、接続できたことも分かりやすくなりました！
問題ないです。

2021-05-29 12:50 UTC, KituneUdon approved these changes
正常に動いたので問題ないです
mergeお願いします

2021-06-18 14:54 UTC, merged